apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app1
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app1
  template:
    metadata:
      labels:
        app: app1
    spec:
      containers:
      - image: artifactory/app1:0.3.4
        name: app1
        ports:
        - containerPort: 8080
        env:
        - name: CLIENT_ADDRESS
          value: http://app2:8080/ws
        - name: CLIENT_SENDER_ID
          value: APP1
