apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: app2
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      labels:
        app: app2
    spec:
      containers:
      - image: artifactory/app2:1.1.5
        name: app2
        ports:
        - containerPort: 8080
        env:
        - name: SERVER_PORT
          value: "8080"
